# /etc/salt/master.d/vault.conf
# CORRECTED with right IP address

vault:
  auth:
    method: approle
    role_id: <in Vault: auth/approle/role/salt-master>
    secret_id: <in Vault: auth/approle/role/salt-master>
  server:
    url: http://192.168.0.25:8200
  issue:
    type: approle
  policies:
    assign:
      - salt_minion
      - salt-minion_{minion}
      - salt-minion_{pillar[roles]}

  metadata:
    entity:
      minion-id: '{minion}'
      roles: '{pillar[roles]}'

